import React from 'react';

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 space-y-12">
      <title>Terms of Use & Disclaimer | FinCalc Flow</title>
      <meta name="description" content="Terms of use for FinCalc Flow tools, covering our calculator disclaimer, liability limitations, and educational use policy." />
      <link rel="canonical" href="https://www.fincalcflow.com/terms" />

      {/* Header */}
      <div className="text-center space-y-4">
        <span className="px-3 py-1 bg-indigo-50 text-indigo-600 rounded-full text-xs font-black tracking-wider uppercase inline-block">
          Legal & Disclaimers
        </span>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight flex items-center justify-center gap-3">
          Terms of Use
        </h1>
        <p className="text-slate-500 text-sm">
          Last updated: July 20, 2026
        </p>
      </div>

      {/* Policy Details */}
      <div className="bg-white rounded-3xl p-8 border border-slate-100 shadow-xl shadow-slate-100/50 space-y-8 text-left">
        
        {/* 1. Educational and Informational Purposes Only */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            1. Educational & Informational Purpose Only
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            All calculations, projections, charts, and values provided by the tools on FinCalc Flow (including the Rent vs. Buy Simulator, Trucking Cost Per Mile, Debt Consolidation, and Google AdSense Revenue Planner) are intended solely for <strong>educational and general informational purposes</strong>. 
          </p>
          <p className="text-slate-650 text-sm leading-relaxed">
            The results generated by these tools are estimations based on standard formulaic models and user-input parameters. They do not constitute professional financial, tax, legal, investment, or corporate advice.
          </p>
        </section>

        {/* 2. No Professional Advice Disclaimer */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            2. No Professional Advice
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            You should not make major financial or business commitments solely in reliance on the calculators hosted on this site. Before buying a home, signing a vehicle lease, consolidating personal debt, or investing in digital marketing ventures, you are highly encouraged to consult with a licensed Certified Public Accountant (CPA), certified financial planner, or professional legal advisor.
          </p>
        </section>

        {/* 3. Accuracy and Disclaimer of Warranties */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            3. Accuracy & Warranty Disclaimer
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            While we strive to keep our formulas and mathematical calculations compliant with standard industry methodologies, all services and tools on this website are provided on an <strong>"as is"</strong> and <strong>"as available"</strong> basis. 
          </p>
          <p className="text-slate-650 text-sm leading-relaxed">
            FinCalc Flow makes no representations or warranties of any kind, express or implied, regarding the accuracy, completeness, reliability, suitability, or availability of the calculators or the calculations they perform. Any reliance you place on such information is strictly at your own risk.
          </p>
        </section>

        {/* 4. Limitation of Liability */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            4. Limitation of Liability
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            In no event will FinCalc Flow, its operators, developers, or affiliates be held liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.
          </p>
        </section>

        {/* 5. Acceptable Use Policy */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            5. Acceptable Use
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            You agree to use this website only for lawful purposes. You are prohibited from attempting to scrape, reverse-engineer, disable, or spam the client-side files or scripts. You may not embed these tools inside iframes on other websites without explicit written permission from the administrator.
          </p>
        </section>

        {/* 6. Contact & Inquiries */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">
            6. Questions Regarding Terms
          </h2>
          <p className="text-slate-650 text-sm leading-relaxed">
            If you have questions about this disclaimer, our liability limits, or the terms of using our serverless mathematical simulators, please reach out to us at: <span className="font-mono text-indigo-600 font-bold">terms@fincalcflow.com</span>.
          </p>
        </section>

      </div>
    </div>
  );
}
